// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240518103235_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category 5"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(6732),
                            ImagePath = "product1.jpg",
                            Name = "Product 1",
                            Price = 100m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7053),
                            ImagePath = "product2.jpg",
                            Name = "Product 2",
                            Price = 200m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7055),
                            ImagePath = "product3.jpg",
                            Name = "Product 3",
                            Price = 300m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7057),
                            ImagePath = "product4.jpg",
                            Name = "Product 4",
                            Price = 400m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7059),
                            ImagePath = "product5.jpg",
                            Name = "Product 5",
                            Price = 500m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7061),
                            ImagePath = "product6.jpg",
                            Name = "Product 6",
                            Price = 600m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7063),
                            ImagePath = "product7.jpg",
                            Name = "Product 7",
                            Price = 700m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7064),
                            ImagePath = "product8.jpg",
                            Name = "Product 8",
                            Price = 800m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7066),
                            ImagePath = "product9.jpg",
                            Name = "Product 9",
                            Price = 900m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7068),
                            ImagePath = "product10.jpg",
                            Name = "Product 10",
                            Price = 1000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7070),
                            ImagePath = "product11.jpg",
                            Name = "Product 11",
                            Price = 1100m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7072),
                            ImagePath = "product12.jpg",
                            Name = "Product 12",
                            Price = 1200m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7074),
                            ImagePath = "product13.jpg",
                            Name = "Product 13",
                            Price = 1300m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7075),
                            ImagePath = "product14.jpg",
                            Name = "Product 14",
                            Price = 1400m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 5, 18, 14, 32, 35, 647, DateTimeKind.Local).AddTicks(7077),
                            ImagePath = "product15.jpg",
                            Name = "Product 15",
                            Price = 1500m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("WebApi.Data.Product", b =>
                {
                    b.HasOne("WebApi.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApi.Data.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
