// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240511140119_Init-4")]
    partial class Init4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 11, 18, 1, 19, 76, DateTimeKind.Local).AddTicks(3419),
                            ImagePath = "product1.jpg",
                            Name = "Product 1",
                            Price = 100m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 11, 18, 1, 19, 77, DateTimeKind.Local).AddTicks(418),
                            ImagePath = "product2.jpg",
                            Name = "Product 2",
                            Price = 200m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 5, 11, 18, 1, 19, 77, DateTimeKind.Local).AddTicks(430),
                            ImagePath = "product3.jpg",
                            Name = "Product 3",
                            Price = 300m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 5, 11, 18, 1, 19, 77, DateTimeKind.Local).AddTicks(432),
                            ImagePath = "product4.jpg",
                            Name = "Product 4",
                            Price = 400m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 5, 11, 18, 1, 19, 77, DateTimeKind.Local).AddTicks(433),
                            ImagePath = "product5.jpg",
                            Name = "Product 5",
                            Price = 500m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
